name = "api"
main = "src/backend/worker.ts"
compatibility_date = "2026-03-05"
compatibility_flags = [ "nodejs_compat" ]

[observability]
enabled = true

[[durable_objects.bindings]]
name = "USER_SYNC_DO"
class_name = "UserSyncDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["UserSyncDO"]
